version: '3.8'

services:
  frontend:
    build:
      context: ./frontend 
    ports:
      - "3008:80"  
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://backend:8080
    networks:
      - app-network


  backend:
    build:
      context: ./backendjs  
    ports:
      - "8080:8080" 
    environment:
      - BACKEND_PORT=8080
      - DB_HOST=ep-falling-bush-a59cclwy.us-east-2.aws.neon.tech
      - DB_PORT=5432
      - DB_NAME=realstateshares
      - DB_USER=realstateshares_owner
      - DB_PASSWORD=fncyrQ0leJs2
      - DB_SSL_MODE=require
    depends_on:
      - db
    networks:
      - app-network 

  db:
    image: postgres:13  
    environment:
      POSTGRES_DB: realstateshares
      POSTGRES_USER: realstateshares_owner
      POSTGRES_PASSWORD: fncyrQ0leJs2
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
